### ISSUE TITLE
Extended example

### ISSUE THREAD

**Issue by mrgloom** [ZFTurbo/ZF_UNET_224_Pretrained_Model#5]
Hi, I have created extended example based on your repository:
https://github.com/mrgloom/keras-semantic-segmentation-example

It also use random colors for foreground and background (not like lighter and darker like here https://github.com/ZFTurbo/ZF_UNET_224_Pretrained_Model/blob/master/train_infinite_generator.py#L24 ), one idea behind it is that in that case network can learn 'shape of object' not just 'thresholding and separating background and foreground', also looks like using random colors make problem harder and network converges slower. 

Also I have experienced some problems:
1) Netwoks not always converges on second run with fixed params even for this toy problem, looks like it depens on random seed.
2) Dice loss and jaccard loss are harder to train than binary crossentropy, any ideas why? Network architecture is the same just loss differs, I even tried to load trained weights from binary crossentropy loss network and use them in dice loss network which show high dice coef.

**Comment by ZFTurbo** [comment]
Some user reports that it's better to use Loss = BCE + (1 - Dice)

**Comment by ZFTurbo** [comment]
@flighted, can you provide code you tried to run? Also what is RGR format?

**Comment by flighted** [comment]
I use data of three channels.And label is grayscale. My goal is like this single class segmentation.The code shows as bellow:

image=glob.glob('D:/resnet/data/image/*.jpg')
label=glob.glob('D:/resnet/data/label/*.png')
image.reshape(img_height, img_width, INPUT_CHANNELS)
label.reshape(img_height, img_width, NUMBER_OF_CLASSES)
def batch_generator(batch_size):
    while True:
        imgs_list=[]
        label_list=[]
        for i in range(len(image)):
             imgs_list.append(img_to_array(image[i]))
             label_list.append(img_to_array(label[i]))
        label_list = np.array(label_list, dtype=np.float32)
        label_list /= 255.0 # [0,1]
        label_list=label_list.reshape(batch_size,224*224,3)
        label_list= label_list.reshape(batch_size,img_height*img_width,NUMBER_OF_CLASSES)
        yield imgs_list,label_list
when I use model.fit,it has an error:
![image](https://user-images.githubusercontent.com/20598051/38988294-47ec31e4-4405-11e8-9fc3-815f2c39d5c7.png)
so what should I modify the data? Any idea? thanks!

**Comment by ZFTurbo** [comment]
I don't see the part where you read the image. You tried to reshape the string with path to file.
You can see examples. Here:
https://github.com/ZFTurbo/DrivenData-Identify-Fish-Challenge-2nd-Place-Solution/blob/master/r20_train_unet_for_roi_detection.py
or here:
https://github.com/ZFTurbo/ZF_UNET_224_Pretrained_Model/blob/master/train_infinite_generator.py

**Comment by flighted** [comment]
My data is ready-made,it doesn't need generate.I am confused about how to write the function of load_data. Due to my function of load_data,it always has errors in this sentence(model.fit(image,label, batch_size=5, epochs=1, verbose=1, shuffle=True, callbacks=[modelweight]).I see the example of yours and mrgloom.I try to modify the data ,like your batch_generator.But it doesn't works.
I  use the code to read the image,as bellow:

train=glob.glob('D:/resnet/data/image/*.jpg')
number_of_classes=1
def load_data(path):
    for i in range(len(train)):
        image=load_img(path+'image'+'/'+str(i)+'.jpg')
        label=load_img(path+'label'+'/'+str(i)+'.png')
        image = img_to_array(image)                                   
        label = img_to_array(label)
        image .reshape(224,224,3)
        label.reshape(224,224,number_of_classes)
        return image, label
def batch_generator(batch_size):
    while True:
        image,label=load_data(path)
        imgs_list=[]
        label_list=[]
        for i in range(len(image)):
             imgs_list.append(img_to_array(image[i]))
             label_list.append(img_to_array(label[i]))
        label_list /= 255.0 # [0,1]
        label_list=label_list.reshape(batch_size,224*224,number_of_classes)
       # label_list= label_list.reshape(batch_size,img_height*img_width,NUMBER_OF_CLASSES)
        yield imgs_list,label_list
#generator = ImgProvider('data/')
model = ZF_UNET_224()
model.compile(optimizer=Adam(lr=1e-4), loss='binary_crossentropy', metrics=['accuracy'])
modelweight = ModelCheckpoint('D:/ZF_UNET/unet.hdf5', monitor='loss', verbose=1, save_best_only=True)
model.fit(batch_generator(2), batch_size=5, epochs=1, verbose=1, shuffle=True, callbacks=[modelweight])

it has error :  File "C:\Users\pc\Anaconda3\lib\site-packages\keras\engine\training.py", line 76, in <listcomp>data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
AttributeError: 'generator' object has no attribute 'ndim'

I have no idea of resolving it.

**Comment by ZFTurbo** [comment]
model.fit(batch_generator(2), ... - I don't think it's the right way to use this function. Check how fit() function works. It requires inputs as numpy array, not batch generator function:
https://keras.io/models/model/

**Comment by flighted** [comment]
Hello, I used the numpy array to process the input  and the out ,like(len(imgs),height,width,channels).I save the input as ".npy".But when I look into  the array of the output,.The predictions shows as a white point,not the area. I expect the output is black background and the label is white.The array of the predictions is  one-dimensional.But we use   conv10 = Conv2D(n_classes, (1, 1), activation='sigmoid')(conv9),should we got two-dimensional?
